// src/components/vue/base/fork.vue
<template>
  <a class="fork" href="https://github.com/pomelott/webpack-multi-page-cli">
      <img :src="fork" alt="">
  </a>
</template>
<script>
export default {
    data () {
        return {
            fork: require('images/example/fork.svg')
        }
    }
}
</script>
<style lang='scss'>
.fork{
    position: absolute;
    width: 150px;
    height: 150px;
    top: 0;
    right: 0;
}
</style>

// src/components/react/fork/index.jsx
import React from 'react';
import formImg from 'images/example/fork.svg';
import './fork.scss';
export default function Fork () {
    return (
        <div className="fork">
            <a href="https://github.com/pomelott/webpack-multi-page-cli">
                <img src={formImg} alt="fork-img"/>
            </a>
        </div>
    );
}
